### ISSUE TITLE
Doesn't rename a file

### ISSUE THREAD

**Issue by sandwichsudo** [popomore/rename#1]
Hi, I have tried using the code in your example:

```
var rename = require('rename');
rename('a.js','b.js');
```

And it runs with no error reported, but the file is not renamed.  I tried logging the value returned from the function and it does return 'b.js'. Should it not also be renaming the file in the filesystem? or have i misunderstood the intention of the plugin? thanks

**Comment by popomore** [comment]
Yes, it will not affect on os, you can use `fs.renameSync`.
